version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/crates/runifi-api/dashboard-react"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"
      - "dashboard"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 3
