use std::sync::Arc;

use bytes::Bytes;
use runifi_plugin_api::context::ProcessContext;
use runifi_plugin_api::processor::{Processor, ProcessorDescriptor};
use runifi_plugin_api::property::PropertyDescriptor;
use runifi_plugin_api::relationship::Relationship;
use runifi_plugin_api::result::ProcessResult;
use runifi_plugin_api::session::ProcessSession;
use runifi_plugin_api::{REL_FAILURE, REL_SUCCESS};

const PROP_FILE_SIZE: PropertyDescriptor = PropertyDescriptor::new(
    "File Size",
    "Size of the generated FlowFile content in bytes",
)
.default_value("1024");

const PROP_BATCH_SIZE: PropertyDescriptor =
    PropertyDescriptor::new("Batch Size", "Number of FlowFiles to generate per trigger")
        .default_value("1");

const PROP_DATA_FORMAT: PropertyDescriptor = PropertyDescriptor::new(
    "Data Format",
    "Format of generated data: 'zeros', 'random', or 'text'",
)
.default_value("zeros");

/// Generates FlowFiles with synthetic content for testing and benchmarking.
pub struct GenerateFlowFile {
    counter: u64,
}

impl GenerateFlowFile {
    pub fn new() -> Self {
        Self { counter: 0 }
    }
}

impl Default for GenerateFlowFile {
    fn default() -> Self {
        Self::new()
    }
}

impl Processor for GenerateFlowFile {
    fn on_trigger(
        &mut self,
        context: &dyn ProcessContext,
        session: &mut dyn ProcessSession,
    ) -> ProcessResult {
        let file_size: usize = context
            .get_property("File Size")
            .unwrap_or("1024")
            .parse()
            .unwrap_or(1024);
        let batch_size: usize = context
            .get_property("Batch Size")
            .unwrap_or("1")
            .parse()
            .unwrap_or(1);
        let data_format_prop = context.get_property("Data Format");
        let data_format = data_format_prop.unwrap_or("zeros");

        for _ in 0..batch_size {
            let mut flowfile = session.create();
            self.counter += 1;

            // Generate content based on format.
            let data = match data_format {
                "random" => {
                    use rand::Rng;
                    let mut buf = vec![0u8; file_size];
                    rand::thread_rng().fill(&mut buf[..]);
                    Bytes::from(buf)
                }
                "text" => {
                    let text = format!("FlowFile #{} generated by RuniFi\n", self.counter);
                    let mut buf = text.into_bytes();
                    buf.resize(file_size, b'\n');
                    Bytes::from(buf)
                }
                _ => Bytes::from(vec![0u8; file_size]),
            };

            // Set standard attributes.
            flowfile.set_attribute(
                Arc::from("filename"),
                Arc::from(format!("generated-{}.dat", self.counter).as_str()),
            );
            flowfile.set_attribute(
                Arc::from("mime.type"),
                Arc::from("application/octet-stream"),
            );

            flowfile = session.write_content(flowfile, data)?;
            session.transfer(flowfile, &REL_SUCCESS);
        }

        session.commit();
        Ok(())
    }

    fn relationships(&self) -> Vec<Relationship> {
        vec![REL_SUCCESS, REL_FAILURE]
    }

    fn property_descriptors(&self) -> Vec<PropertyDescriptor> {
        vec![PROP_FILE_SIZE, PROP_BATCH_SIZE, PROP_DATA_FORMAT]
    }
}

inventory::submit! {
    ProcessorDescriptor {
        type_name: "GenerateFlowFile",
        description: "Generates FlowFiles with synthetic content for testing and benchmarking",
        factory: || Box::new(GenerateFlowFile::new()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use runifi_plugin_api::property::PropertyValue;

    struct TestContext {
        file_size: String,
        batch_size: String,
        data_format: String,
    }

    impl ProcessContext for TestContext {
        fn get_property(&self, name: &str) -> PropertyValue {
            match name {
                "File Size" => PropertyValue::String(self.file_size.clone()),
                "Batch Size" => PropertyValue::String(self.batch_size.clone()),
                "Data Format" => PropertyValue::String(self.data_format.clone()),
                _ => PropertyValue::Unset,
            }
        }
        fn name(&self) -> &str {
            "test-generate"
        }
        fn id(&self) -> &str {
            "test-id"
        }
        fn yield_duration_ms(&self) -> u64 {
            1000
        }
    }

    struct CollectorSession {
        transferred: Vec<(runifi_plugin_api::FlowFile, &'static str)>,
        written_data: Vec<Bytes>,
        next_id: u64,
    }

    impl CollectorSession {
        fn new() -> Self {
            Self {
                transferred: Vec::new(),
                written_data: Vec::new(),
                next_id: 1,
            }
        }
    }

    impl ProcessSession for CollectorSession {
        fn get(&mut self) -> Option<runifi_plugin_api::FlowFile> {
            None
        }
        fn get_batch(&mut self, _max: usize) -> Vec<runifi_plugin_api::FlowFile> {
            vec![]
        }
        fn read_content(&self, _ff: &runifi_plugin_api::FlowFile) -> ProcessResult<Bytes> {
            Ok(Bytes::new())
        }
        fn write_content(
            &mut self,
            mut ff: runifi_plugin_api::FlowFile,
            data: Bytes,
        ) -> ProcessResult<runifi_plugin_api::FlowFile> {
            ff.size = data.len() as u64;
            self.written_data.push(data);
            Ok(ff)
        }
        fn create(&mut self) -> runifi_plugin_api::FlowFile {
            let id = self.next_id;
            self.next_id += 1;
            runifi_plugin_api::FlowFile {
                id,
                attributes: Vec::new(),
                content_claim: None,
                size: 0,
                created_at_nanos: 0,
                lineage_start_id: id,
                penalized_until_nanos: 0,
            }
        }
        fn clone_flowfile(
            &mut self,
            _ff: &runifi_plugin_api::FlowFile,
        ) -> runifi_plugin_api::FlowFile {
            unimplemented!()
        }
        fn transfer(&mut self, ff: runifi_plugin_api::FlowFile, rel: &Relationship) {
            self.transferred.push((ff, rel.name));
        }
        fn remove(&mut self, _ff: runifi_plugin_api::FlowFile) {}
        fn penalize(&mut self, ff: runifi_plugin_api::FlowFile) -> runifi_plugin_api::FlowFile {
            ff
        }
        fn commit(&mut self) {}
        fn rollback(&mut self) {}
    }

    #[test]
    fn generates_flowfiles() {
        let mut proc = GenerateFlowFile::new();
        let ctx = TestContext {
            file_size: "5120".to_string(),
            batch_size: "3".to_string(),
            data_format: "zeros".to_string(),
        };
        let mut session = CollectorSession::new();

        proc.on_trigger(&ctx, &mut session).unwrap();

        assert_eq!(session.transferred.len(), 3);
        for (ff, rel) in &session.transferred {
            assert_eq!(*rel, "success");
            assert_eq!(ff.size, 5120);
            assert!(ff.get_attribute("filename").is_some());
        }
    }

    #[test]
    fn random_data_is_not_zeros() {
        let mut proc = GenerateFlowFile::new();
        let ctx = TestContext {
            file_size: "1024".to_string(),
            batch_size: "1".to_string(),
            data_format: "random".to_string(),
        };
        let mut session = CollectorSession::new();

        proc.on_trigger(&ctx, &mut session).unwrap();

        assert_eq!(session.written_data.len(), 1);
        let data = &session.written_data[0];
        assert_eq!(data.len(), 1024);
        // Random data should not be all zeros.
        let non_zero_count = data.iter().filter(|&&b| b != 0).count();
        assert!(
            non_zero_count > 0,
            "Random data should contain non-zero bytes"
        );
    }
}
